services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: node-app-3225
    container_name: running-app

    ports:
      - "3225:3225"

    env_file:
      - .env

    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      LOKI_HOST: http://loki:3100
      KAFKA_BROKERS: redpanda:9092
      # Redis
      REDIS_URL: redis://redis:6379

    networks:
      - monitoring
      - erp-core-net
      - backend-core-net
      - redis-core-network

    restart: unless-stopped

networks:
  monitoring:
    external: true
    name: monitoring_default

  erp-core-net:
    external: true

  backend-core-net:
    external: true

  redis-core-network:
    external: true
